global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: flink-jobmanager
    static_configs:
      - targets: ["jobmanager:9249"]

  - job_name: flink-taskmanagers
    static_configs:
      - targets:
          - "taskmanager-1:9249"
          - "taskmanager-2:9249"
